### ISSUE TITLE
Fix Build Process

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquity-dollar#7]
Right now the build process is broken and hacked together quickly. It currently is invoked using `yarn dev` and handles a bunch of steps but seems to have issues.

@Zequez consult with @zgorizzo69 to make sure the build steps are correct.

@zgorizzo69 please add to this list if I am missing steps as I do not fully grasp the steps. I understand that it's important to do the following: 

- [ ] clone in the `uad-contracts` repo, 
- [ ] compile the contracts to generate the artifact, 
- [ ] generate typescript typings
- [ ] make the artifact accessible by the frontend/ui for ethers to interface with
- [ ] compile the frontend

**Comment by 0x4007** [comment]
@zapaz I just remembered that I believe we started having issues after you added the new smart contract I think it was Masterchef v2.1 ? @zgorizzo69 can you verify what the situation is here, explain to @Zequez and he can fix?

I'm running `yarn dev` and its hanging here:

<img width="1366" alt="Screen Shot 2021-09-04 at 19 40 24" src="https://user-images.githubusercontent.com/4975670/132111312-d142785d-2c9e-4015-a250-504e55c7019f.png">

**Comment by 0x4007** [comment]
Update: here's the issue in the logs. Basically I need to be able to generate the artifact, and then load it in the front end user interface.

```shell
yarn run v1.22.10
$ $PATH/repos/ubiquity/uad/ui/contracts/node_modules/.bin/hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/UA3XUxL5eR2FY8wd4IO203zS-svtiYAa --fork-block-number 12150000 --show-accounts --export-all tmp-uad-contracts-deployment.json
Nothing to compile
Creating Typechain artifacts in directory artifacts/types for target ethers-v5
Successfully generated Typechain artifacts!
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
deploying "UbiquityAlgorithmicDollarManager" (tx: 0x560c7bec9212e56c1972dc8769230a1619cc5ecf5814732d7f6a61854115bfac)...: deployed at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6 with 2235675 gas
deploying "Bonding" (tx: 0xb2ae5ac6f1217f977a119a14289a188eb4906d967f90962621d6fcee30a28254)...: deployed at 0x8A777ACB51217Cd8d8f5D05D05dF334989eA976C with 3403953 gas
Bonding deployed at: 0x8A777ACB51217Cd8d8f5D05D05dF334989eA976C
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
reusing "UbiquityAlgorithmicDollarManager" at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6
deploying "BondingShare" (tx: 0x7c13a7446a102bf47e62ddbc5a97997ebd1607d76b0bee274a771ef957219d3c)...: deployed at 0x07860015449240D2f20c63AF68b64cB0a2EA91Ee with 2500713 gas
BondingShare deployed at: 0x07860015449240D2f20c63AF68b64cB0a2EA91Ee
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
reusing "UbiquityAlgorithmicDollarManager" at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6
deploying "BondingShareV2" (tx: 0x9929f7be8cf97939075416d80abd0a4ad75f4e8a177f6e1007f992b2c7a93684)...: deployed at 0x083EB03aEcBb3Ff24a08256D65F35157fb248CD7 with 2693711 gas
BondingShareV2 deployed at: 0x083EB03aEcBb3Ff24a08256D65F35157fb248CD7
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
reusing "UbiquityAlgorithmicDollarManager" at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6
deploying "CouponsForDollarsCalculator" (tx: 0xaf03ed9ec5521fd78b1b1f44fddc6ef62b27dc84634b616ba7f94a5c6a2d43de)...: deployed at 0x369ea2eA2bC03487881EEf983F6B3C7B947bA9f6 with 1016350 gas
CouponsForDollarsCalculator deployed at: 0x369ea2eA2bC03487881EEf983F6B3C7B947bA9f6
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
reusing "UbiquityAlgorithmicDollarManager" at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6
deploying "CurveUADIncentive" (tx: 0x454ffc138e4460acd242e6ac35ab6bb7b59af854b4a0377b3397ba4fee878c74)...: deployed at 0xA69bE6aC7733D2D43BdD6d768EA8E99fa2bFd915 with 1661675 gas
CurveUADIncentive deployed at: 0xA69bE6aC7733D2D43BdD6d768EA8E99fa2bFd915
admin address : 0xC8D95470e57159d85e6d2241fb47474653aee7F7
reusing "UbiquityAlgorithmicDollarManager" at 0x869e954f9bd9e8c5dA8a7c770EfCb2fF43882bf6
deploying "DebtCoupon" (tx: 0x2a21c7fca14c6a8f7ca9978d02e7d19fcb2ca5d1bef07abbeebc046935d8fb60)...: deployed at 0x8b9d9b099A9ae40987F27970f88eF8eE3C9FeEbB with 2956681 gas
DebtCoupon deployed at: 0x8b9d9b099A9ae40987F27970f88eF8eE3C9FeEbB
Manager DebtCoupon address at: 0x8b9d9b099A9ae40987F27970f88eF8eE3C9FeEbB
Will update manager DebtCoupon address from: 0x0000000000000000000000000000000000000000  to: 0x8b9d9b099A9ae40987F27970f88eF8eE3C9FeEbB
Press any key to continue
Error HH604: Error running JSON-RPC server: ERROR processing $PATH/repos/ubiquity/uad/ui/contracts/deploy/DebtCoupon.ts:
TypeError: process.stdin.setRawMode is not a function
    at $PATH/repos/ubiquity/uad/ui/contracts/utils/flow.ts:6:19
    at new Promise (<anonymous>)
    at Object.pressAnyKey [as default] ($PATH/repos/ubiquity/uad/ui/contracts/utils/flow.ts:4:10)
    at Object.func ($PATH/repos/ubiquity/uad/ui/contracts/deploy/DebtCoupon.ts:51:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
    at DeploymentsManager.executeDeployScripts ($PATH/repos/ubiquity/uad/ui/contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1049:22)

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 0x4007** [comment]
Update: I tried running it in interactive mode to get around the previous bug and I got the following issue:

```
MasterChefV2.1 deployer: 0xefC0e701A824943b469a694aC564Aa1efF7Ab7dd
Error HH604: Error running JSON-RPC server: ERROR processing $HOME/repos/ubiquity/uad/ui/contracts/deploy/MasterChefV2.1.ts:
Error: Transaction reverted: function call to a non-contract account
    at MasterChefV2._getTwapPrice (contracts/MasterChefV2.sol:312)
    at MasterChefV2._updateUGOVMultiplier (contracts/MasterChefV2.sol:247)
    at MasterChefV2.constructor (contracts/MasterChefV2.sol:101)
    at EthModule._estimateGasAction ($HOME/repos/ubiquity/uad/ui/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:429:9)
    at HardhatNetworkProvider.request ($HOME/repos/ubiquity/uad/ui/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:106:18)
```

**Comment by 0x4007** [comment]
Current status at PR #8 

@zgorizzo69 pick up where I'm leaving off by jumping into my pull request. I couldn't figure out how to fix @zapaz `MasterChefV2.1.ts`

My command to invoke this is 
```yarn hardhat node --show-stack-traces --fork https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_KEY --fork-block-number 12150000 --show-accounts --export-all tmp-uad-contracts-deployment.json```

**Comment by zapaz** [comment]
As I remember, the problem comes from the build process that requires to make a "fake" deploy to get good artifacts for the UI ...

The reason why the "fake" deploy doesn't work, is basically due to blockchain movements (as we have to move starting block after MasterChefV2.1 block deployment)  : some impersonated wallets used have no more enough balance, some contracts have changed, and so on...

I did try to solve these issues in this branch : https://github.com/ubiquity/uad-contracts/tree/fixDeployOnRecentBlock
But get blocked on last issue... anyway, this "fake" deploy is not needed at all

You have just to use a script like  "npx hardhat export" 

(all this has been commented in Discord channel during the fix)

**Comment by zapaz** [comment]
here is the exact script used ,  Discord chanel "zapaz", 11/08/2021 : 

`npx hardhat export --export ../frontend/src/full_deployment.json --network mainnet`

**Comment by Zequez** [comment]
Should we mark this issue as resolved?
